package twintro.minecraft.modbuilder.data.resources;

/**
 * enum containing all block materials in minecraft.
 * This enum was generated by the ResourceHelper class.
 * Block materials contain properties such as sound when breaking a block or flammability.
 */
public enum MaterialResource {
	air, grass, ground, wood, rock, iron, anvil, water, lava, leaves, plants, vine, sponge, cloth, fire, sand, circuits, carpet, glass, redstone_light, tnt, coral, ice, packed_ice, snow, crafted_snow, cactus, clay, gourd, dragon_egg, portal, cake, web, piston, barrier,
}
