package twintro.minecraft.modbuilder.data.resources;

/**
 * enum containing all creative tabs in minecraft.
 * This enum was generated by the ResourceHelper class.
 */
public enum TabResource {
	block, decorations, redstone, transport, misc, all_search, food, tools, combat, brewing, materials, inventory,
}
